### PR TITLE
Add a JSON extention

### PR DESCRIPTION
**Pull request by Azzaare**
Currently, converts an XML file/string to JSON while keeping attributes (including duplicates).

Credits: @oxinabox for the original script for this

EDIT: credits

### CODE REVIEW

**Comment by Azzaare** [comment]
Hmm, Extensions are not supported for the current LTS.

Is it okay to improve Julia requirement to 1.9 ? Otherwise, I need to understand how to handle Require.jl...

EDIT: Opted for ignoring the extensions for versions of Julia before 1.9 (TIL)

**Comment by oxinabox** [comment]
I don't really understand the need for this in this package.
It might make sense as an example to put in the docs?

**Comment by Azzaare** [comment]
Oh, I thought it could be useful for other people (some mentioned the need for it in Slack). I just thought it would be convenient to have it somewhere ...

I don't mind either way, as I can put it as a utility function in the package I am making that requires it.

**Comment by joshday** [comment]
Yeah, I like the functionality but I think this is outside the scope of this package.

**Pull request closed without merging**
