### PR TITLE
Add support for Julia 1.6

### PR DESCRIPTION
**Pull request by stemann**

### CODE REVIEW

**Comment by stemann** [comment]
@joshday Care to comment?

**Comment by joshday** [comment]
Ah, thanks for the reminder.  Lost track of this.

**Comment by stemann** [comment]
Excellent, thank you! :-)

Can we get a1e739b456d3efe7952b9a2acc52d09698637b4c registered too? :-)

**Comment by stemann** [comment]
Bump, nudge :-)

**Comment by joshday** [comment]
Done!  (thanks for the nudge)

**Pull request merged**
